# Generated by Django 6.0.4 on 2026-05-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, help_text='Nahrajte miniaturu kurzu', null=True, upload_to='media/course_imgs', verbose_name='Miniatura kurzu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Nahrajte profilovou fotku', null=True, upload_to='media/profile-pics', verbose_name='Profilová fotka'),
        ),
    ]
