# Generated by Copilot on 2026-05-25

from django.db import migrations, models


def forwards_copy_categories(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    db_alias = schema_editor.connection.alias
    through_model = Course.categories.through

    for course in Course.objects.using(db_alias).all():
        category_id = getattr(course, "category_id", None)
        if category_id:
            through_model.objects.using(db_alias).get_or_create(
                course_id=course.course_id,
                category_id=category_id,
            )


def backwards_copy_categories(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    db_alias = schema_editor.connection.alias

    for course in Course.objects.using(db_alias).all():
        categories = list(course.categories.all())
        if categories:
            course.category_id = categories[0].category_id
            course.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_img_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="courses.category",
                verbose_name="Kategorie",
                help_text="Vyberte kategorie kurzu",
            ),
        ),
        migrations.RunPython(forwards_copy_categories, backwards_copy_categories),
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
    ]
