# Generated by Django 6.0.4 on 2026-05-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_categories_m2m'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS course_categor_16662e_idx",
                    reverse_sql="CREATE INDEX IF NOT EXISTS course_categor_16662e_idx ON course (category_id)",
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="course",
                    name="course_categor_16662e_idx",
                ),
            ],
        ),
    ]
