# Generated by Copilot on 2026-05-25

from django.conf import settings
from django.db import migrations, models


def create_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("courses", "UserProfile")
    db_alias = schema_editor.connection.alias

    for user in User.objects.using(db_alias).all():
        UserProfile.objects.using(db_alias).get_or_create(user_id=user.id)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_course_categor_16662e_idx"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("student", "Student"), ("teacher", "Teacher")], default="student", help_text="Select user role", max_length=10, verbose_name="Role")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno")),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="Upraveno")),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="user_profile_role_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["created_at"], name="user_profile_created_idx"),
        ),
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(blank=True, help_text="Uživatel, který kurz vytvořil", null=True, on_delete=models.deletion.SET_NULL, related_name="courses_created", to=settings.AUTH_USER_MODEL, verbose_name="Vytvořil"),
        ),
    ]
